config/routes.rb
MessageLocation::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "locations/show"

  match "checkin/:checkinid" => "checkins#show"

  match "foursquare/incoming" => 'foursquare#push'

  resources :messages

  get "/nearby", :to => "messages#nearby"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get "login",   :to => "devise/sessions#new"
    get "signout", :to => "devise/sessions#destroy"
    get "signup",  :to => "devise/registrations#new"
  end

  root :to => "static_pages#home"

end

app/views/layouts/_flash.html.erb
<% unless notice.nil? %><p class="notice"><%= notice %></p><% end %>
<% unless alert.nil? %><p class="alert"><%= alert %></p><% end %>

app/views/layouts/_footer.html.erb
<footer id="f">
  <div class="container">
    <div class="footer-links">
      <% if user_signed_in? %>
        <%= link_to "Log out", signout_path %>
        <%= link_to "Edit profile", edit_user_registration_path(current_user) %>
      <% end %>
    </div>
    <div class="foursquare-logo-container center">
      <%= link_to image_tag("powered-by-foursquare.png", height: 20), "http://foursquare.com", class: "foursquare-logo" %>
    </div>
    <div class="contact-links">
        <a href="mailto:ty.pearson@gmail.com">Comments, suggestions, etc.</a>
    </div><!--end .contact-links -->
  </div><!--end .container -->
</footer><!--end #f -->

app/views/layouts/_header.html.erb
  <header id="h">
    <div class="container cf">
      <div class="left logo-area">
        <h1 class="logo"><i class="icon-comments-alt"></i> <%= link_to 'Remigeo', root_path %></h1>
      </div><!--end .logo -->
      <div class="right header-bonus">
        <% if user_signed_in? %>
        <div class="search">
          <%= form_tag messages_path, :method => 'get' do %>
            <%= search_field_tag :search, params[:search], :placeholder => "Search notes" %>
          <% end %>
        </div><!--end .search -->
        <% end %>
        <div class="header-buttons">
        <% if user_signed_in? %>
          <a class="button header-button" href="/messages/new"><i class="icon-pencil"></i> <span class="hide-mobile">Add New</span></a>
        <% else %>
          <%= link_to '<i class="icon-foursquare"></i>Sign in with Foursquare'.html_safe, user_omniauth_authorize_path(:foursquare), :class => "button header-button" %>
        <% end %>
        </div><!-- .header-buttons -->
      </div><!--end .header-bonus -->
    </div><!--end .container -->
  </header><!--end .header -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset=utf-8>
  <title><%= full_title(yield(:title)).html_safe %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>

  <!-- make it responsive -->
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">

  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  <%= include_gon %>

  <% if user_signed_in? %>
  <%= javascript_include_tag "application" %>
  <% end %>

  <% if !Rails.env.development? %>
    <!-- typekit for remigeo.com -->
    <script src="//use.typekit.net/gsg6lie.js"></script>
    <script>try{Typekit.load();}catch(e){}</script>
  <% end %>

  <% if Rails.env.production? %>
    <!-- analytics -->
    <script>
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-11559286-31']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>
  <% end %>

  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class(yield(:body_class)) %> <%= controller_name %> <%= action_name %>">

  <%= render 'layouts/header' %>
  <%= render 'layouts/flash' %>

  <div class="container fluff">
    <section id="main">
      <%= yield %>
    </section><!-- end #main -->
  </div><!--end .container -->

  <%= render 'layouts/footer' %>

</body>
</html>